INSERT INTO Movie_Cast(id, gender, name) VALUES ("14", "2", "Tom Hanks");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("15", "2", "Tim Allen");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("16", "2", "Don Rickles");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("17", "2", "Jim Varney");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("18", "2", "Wallace Shawn");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("19", "2", "John Ratzenberger");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("20", "1", "Annie Potts");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("26", "0", "John Morris");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("22", "2", "Erik von Detten");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("23", "1", "Laurie Metcalf");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("24", "2", "R. Lee Ermey");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("25", "1", "Sarah Freeman");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("27", "2", "Penn Jillette");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1", "2", "Robin Williams");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("8", "2", "Jonathan Hyde");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("2", "1", "Kirsten Dunst");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("10", "1", "Bonnie Hunt");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("11", "1", "Patricia Clarkson");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("13", "1", "Laura Bell Bundy");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("31", "2", "James Handy");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("12", "1", "Gillian Barber");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("28", "2", "Brandon Obray");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("29", "0", "Cyrus Thiedeke");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("30", "0", "Gary Joseph Thorup");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("32", "0", "Leonard Zola");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("33", "2", "Lloyd Berry");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("34", "2", "Malcolm Stewart");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("35", "0", "Annabel Kershaw");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("36", "2", "Darryl Henriques");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("37", "0", "Robyn Driscoll");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("50", "2", "Peter Bryant");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("39", "0", "Sarah Gilson");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("40", "0", "Florica Vlad");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("41", "0", "June Lion");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("42", "0", "Brenda Lockmuller");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("3", "2", "Jack Lemmon");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("4", "1", "Ann-Margret");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("5", "1", "Sophia Loren");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("6", "1", "Daryl Hannah");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("9", "2", "Burgess Meredith");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("21", "2", "Wesley Snipes");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("38", "1", "Natalie Portman");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("46", "2", "Danny Trejo");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("47", "2", "Henry Rollins");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("43", "2", "Kevin Gage");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("44", "1", "Susan Traylor");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("48", "2", "Jerry Trimble");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("54", "2", "Jeremy Piven");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("55", "2", "Xander Berkeley");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("51", "1", "Begonya Plaza");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("56", "2", "Rick Avery");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("52", "0", "Hazelle Goodman");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("53", "2", "Ray Buktenica");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("59", "0", "Max Daniels");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("60", "0", "Vince Deadrick Jr.");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("96", "2", "Steven Ford");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("97", "1", "Farrah Forke");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("99", "1", "Patricia Healy");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("100", "2", "Paul Herman");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("101", "1", "Cindy Katz");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("102", "0", "Brian Libby");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("104", "2", "Dan Martin");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("109", "0", "Mario Roberts");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("110", "0", "Thomas Rosales, Jr.");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("112", "1", "Yvonne Zima");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("116", "0", "Mick Gould");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("115", "2", "Bud Cort");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("123", "0", "Viviane Vives");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("45", "1", "Kim Staunton");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("49", "2", "Martin Ferrero");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("57", "0", "Brad Baldridge");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("58", "0", "Andrew Camuccio");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("94", "0", "Kenny Endoso");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("95", "1", "Kimberly Flynn");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("98", "0", "Niki Harris");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("103", "0", "Bill McIntosh");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("105", "0", "Rick Marzan");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("106", "0", "Terry Miller");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("107", "0", "Daniel O'Haco");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("111", "1", "Kai Soremekun");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("113", "0", "Peter Blackwell");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("114", "0", "Trevor Coppola");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("118", "1", "Mary Kircher");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("119", "0", "Darin Mangan");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("120", "2", "Robert Miranda");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("121", "2", "Manny Perry");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("122", "1", "Iva Franks Singer");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("124", "0", "Tim Werner");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("133", "2", "Philip Ettington");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("61", "2", "John C. Vennema");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("62", "1", "Margo Martindale");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("63", "1", "J. Smith-Cameron");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("64", "1", "Christine Luneau-Lipton");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("65", "2", "Michael Dees");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("66", "0", "Denis Holmes");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("67", "1", "Jo-Jo Lowe");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("68", "0", "Ira Wheeler");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("69", "1", "Philippa Cooper");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("70", "1", "Ayako Kawahara");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("71", "0", "François Genty");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("72", "2", "Guillaume Gallienne");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("73", "1", "Inés Sastre");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("74", "0", "Phina Oruche");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("75", "1", "Andrea Behalikova");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("76", "1", "Jennifer Herrera");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("77", "1", "Kristina Kumlin");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("78", "1", "Eva Linderholm");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("79", "1", "Carmen Chaplin");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("80", "1", "Micheline Van de Velde");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("81", "1", "Joanna Rhodes");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("82", "2", "Alan Boone");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("83", "0", "Patrick Forster-Delmas");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("84", "2", "Kentaro Matsuo");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("85", "0", "Peter McKernan");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("86", "2", "Ed Connelly");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("87", "2", "Ronald L. Schwary");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("88", "2", "Alvin Lum");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("89", "1", "Siching Song");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("90", "0", "Phil Nee");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("91", "2", "Randy Becker");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("92", "1", "Susan Browning");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("93", "2", "Anthony Mondal");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("7", "2", "Eric Schweig");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("175", "0", "Michael Chance");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("176", "2", "Vernon Campbell");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("177", "0", "H. Michael Walls");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("178", "0", "Bob Adrian");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("179", "2", "Simon Jones");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("180", "0", "Carol Florence");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("181", "2", "Bill Raymond");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("182", "2", "Ernest Abuba");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("183", "1", "Irma St. Paule");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("186", "2", "Rozwill Young");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("187", "1", "Nell Johnson");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("188", "0", "Frederick Strother");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("189", "0", "Charles Techman");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("191", "2", "Rick Warner");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("192", "2", "Anthony 'Chip' Brienza");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("184", "2", "Bruce Kirkpatrick");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("185", "0", "Wilfred Williams");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("193", "1", "Joilet Harris");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("194", "1", "Drucie McDaniel");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("195", "2", "John Blaisse");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("196", "2", "Louis Lippa");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("197", "2", "Stan Kang");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("198", "2", "Pat Dias");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("199", "2", "Felix Pire");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("200", "2", "Karl Warren");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("201", "2", "Joseph McKenna");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("202", "2", "Stephen Bridgewater");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("203", "2", "Ray Huffman");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("204", "2", "Charley Scalies");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("205", "2", "Robert O'Neill");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("206", "2", "Paul Meshejian");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("207", "2", "Kevin Thigpen");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("208", "0", "Harry O'Toole");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("220", "1", "Jann Ellis");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("224", "2", "Michael Ryan Segal");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("209", "2", "Korchenko");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("210", "2", "Chuck Jeffreys");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("218", "2", "Barry Price");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("219", "2", "John Panzarella");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("221", "1", "Janet Zappala");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("223", "1", "Lisa Talerico");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("211", "1", "Tiffany Baldwin");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("212", "2", "C.J. Byrnes");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("213", "2", "Tom Detrik");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("214", "2", "Joe Gerety");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("215", "1", "Renee Spei");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("216", "1", "Bonnie Loev");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("217", "0", "Raymond Mamrak");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("222", "2", "Sal Mazzotta");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("225", "2", "Allelon Ruggiero");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("226", "2", "Thang");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("108", "2", "Bob Stephenson");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("117", "1", "Rachel Flanagan");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("139", "2", "Brian Evers");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("125", "2", "Arthur Max");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1001", "0", "Aida Mohammadkhani");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1002", "0", "Mohsen Kafili");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1003", "0", "Fereshteh Sadre Orafaiy");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1006", "0", "Anna Borkowska");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1007", "0", "Mohammad Shahani");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("127", "0", "Julie Austin");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1004", "0", "Najia Ouerghi");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1008", "0", "Sabah Bouzouita");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1020", "1", "Hend Sabry");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("128", "2", "Michael Leader");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("126", "2", "Jeremy Sinden");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("129", "0", "Colin Higgins");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1005", "0", "Akira Takayama");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1024", "0", "Christianne Mays");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("130", "2", "Michael McFall");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("131", "2", "Byron Minns");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("132", "2", "Stephen Bridgewater");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("134", "0", "Isabel Rose");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("135", "0", "Richard D'Alessandro");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("136", "2", "Michael Jace");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("137", "2", "Geoffrey Blake");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("138", "1", "Vanessa Roth");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("140", "0", "Tiffany Salerno");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("141", "0", "Tiffany Salerno");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("142", "2", "Joe Alaskey");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("143", "0", "Lazarus Jackson");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("144", "0", "Lazarus Jackson");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("145", "0", "Nora Dunfee");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("146", "0", "Hallie D'Amore");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("147", "2", "Michael Mattison");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("148", "2", "Charles Boswell");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("149", "2", "Timothy McNeil");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("150", "0", "Greg Brown");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("151", "2", "Troy Christian");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("152", "2", "Bryan Hanna");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("153", "0", "Zach Hanner");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("154", "0", "Aaron Michael Lacey");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("155", "1", "Jacqueline Lovell");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("157", "0", "Brendan Shanahan");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("158", "0", "William Shipman");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("159", "2", "Robb Skyler");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("160", "0", "Mary Ellen Trainor");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1000", "0", "Steve Alden");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1009", "2", "Duane Martin");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1010", "1", "Robin Givens");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1011", "2", "Marco Hofschneider");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1012", "0", "Rick Johnson");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1013", "1", "Charlotte Ross");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1014", "2", "Edward Herrmann");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1015", "2", "Jack Coleman");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1016", "2", "Charles S. Dutton");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1017", "2", "Hinton Battle");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1018", "1", "Ruth Williamson");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1019", "2", "Michael Reilly Burke");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("0", "2", "James Russo");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("156", "2", "Russ Powell");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("161", "0", "Gohr Van Vleck");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("162", "0", "Myrtle Rishell");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("163", "2", "Benny Rubin");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("164", "2", "Shimen Ruskin");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("165", "2", "George Sherwood");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("166", "0", "Edward Ryan");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("167", "2", "Landers Stevens");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("168", "0", "Harry J. Vejar");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("169", "0", "Tudor Williams");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("170", "0", "Arthur Yeoman");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("190", "0", "Charles Bennett");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("171", "0", "Shirley Lew");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("172", "0", "Tien-Lang Li");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("173", "0", "Baron James Lichter");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("174", "2", "Marco López");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("227", "0", "Charles Schaeffer");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("228", "0", "Fred Scheiwiller");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("229", "2", "Eddie Searles");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("230", "2", "Scott Seaton");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("231", "0", "Bernard Sell");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("232", "0", "Sammy Shack");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("233", "0", "Leslie Sketchley");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("234", "0", "June Smaney");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("235", "1", "Mabel Smaney");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("236", "0", "J. Lewis Smith");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("237", "0", "Charles Soldani");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("238", "0", "Stephen Soldi");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("239", "0", "Kalu K. Sonkur");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("240", "0", "Hayward Soo Hoo");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("241", "0", "Walter Soo Hoo");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("242", "0", "Ray Spiker");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("243", "0", "Robert St. Angelo");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("244", "0", "John Starck");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("245", "0", "Norman Stevans");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("246", "0", "Bert Stevens");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("247", "2", "Jack Stoney");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("248", "0", "Ramón Sánchez");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("249", "2", "Mike Tellegen");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("250", "0", "Lillian Ten Eyck");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("251", "0", "Jack Tornek");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("252", "0", "Arthur Tovey");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("253", "2", "Michael Trubshawe");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("254", "0", "Tony Urchel");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("255", "0", "Sailor Vincent");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("256", "1", "Sally Yarnell");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("257", "0", "William Yokota");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("258", "1", "Mary Young");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("259", "2", "Richard Aherne");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("260", "0", "Frank Baker");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("261", "0", "John Benson");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("262", "0", "Albert Cavens");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("263", "0", "Fred Cavens");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("264", "0", "Cecil Combs");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("265", "0", "Ashley Cowan");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("266", "0", "Roy Darmour");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("267", "2", "Leslie Denison");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("268", "0", "Carli Elinor");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("269", "0", "Raoul Freeman");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("270", "0", "Rudy Germane");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("271", "0", "Arthur Gould-Porter");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("272", "2", "Cameron Hall");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("273", "2", "Chuck Hamilton");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("274", "0", "Roddy Hughes");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("275", "1", "Joanna Marie Jones");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("276", "2", "Weaver Levy");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("277", "0", "Fateh Lohani");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("278", "0", "Joan Lora");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("279", "0", "Manuel López");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("280", "2", "William Meader");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("281", "2", "Jack Mulhall");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("282", "0", "Satini Pualoa");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("283", "0", "Bill Shine");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("284", "0", "Bhogwan Singh");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("285", "0", "Cap Somers");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("286", "2", "Philip Van Zandt");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("287", "1", "Carol White");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("288", "2", "Bob Whitney");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("290", "0", "Al Bain");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("292", "2", "Noble Chissell");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("295", "0", "Alphonso DuBois");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("289", "2", "Philip Ahn");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("306", "2", "Richard Loo");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("291", "2", "Chet Brandenburg");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("293", "0", "Martin Cichy");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("294", "2", "Campbell Cotts");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("297", "2", "Felix Felton");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("305", "2", "Frederick Leister");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("308", "0", "Norman Macowan");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("296", "0", "Adolph Faylauer");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("309", "0", "Russell Meeker");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("298", "2", "Duke Fishman");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("299", "2", "John George");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("300", "0", "Al Haskell");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("301", "0", "Tex Holden");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("302", "2", "Charles Horvath");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("311", "0", "Boyd 'Red' Morgan");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("303", "0", "Shep Houghton");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("304", "2", "Walter Kingsford");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("307", "2", "Keye Luke");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("310", "0", "Frank Mills");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("312", "2", "Manuel París");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("313", "2", "Jack Perrin");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("315", "0", "Robert Robinson");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("316", "0", "Edwin Rochelle");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("317", "0", "Phil Schumacher");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("318", "2", "Dick Wessel");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("319", "0", "Zamba The Lion");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("347", "1", "Suzanne Ridgeway");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("348", "1", "Winona Smith");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1058", "1", "Clea DuVall");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1060", "2", "Ryan Reynolds");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1021", "0", "Danny Harris");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1022", "1", "Jenifer Lewis");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1051", "1", "Roseanne Barr");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1025", "2", "Jeff Margolis");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1026", "1", "Salma Hayek");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1027", "0", "Dora Mendoza");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1028", "0", "Paul Guerro");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1029", "0", "Henne Vilanch");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1030", "1", "Michele Lee");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1031", "2", "Billy Crystal");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1032", "0", "George Schlatter");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1033", "0", "Stephen Pouliot");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1034", "0", "Susan Futterman");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1035", "2", "Marc Shaiman");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1036", "0", "Michael Smith");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1037", "0", "James Loyce");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1038", "0", "Don Scotti");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1039", "1", "Christine Baranski");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1040", "2", "Tim Curry");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1041", "1", "Traci Lords");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1042", "0", "Tom Vergron");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1043", "2", "David Copperfield");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1044", "1", "Margaret Cho");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1045", "1", "Beverly D'Angelo");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1046", "1", "Ali MacGraw");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1047", "1", "Lauren Bacall");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1048", "1", "Merry Clayton");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1050", "1", "Sigourney Weaver");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1052", "2", "Robin Williams");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1023", "2", "Frank Oz");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1056", "1", "Fran Brill");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1057", "2", "Kirk R. Thatcher");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1049", "1", "Jeannie Rapp");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1053", "1", "Trisha Tiedemann");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1054", "1", "Janet Thomas");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1055", "1", "Janet Wieringa");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1059", "1", "Elaina Doucet");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1061", "0", "Johann K. Petursson");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1062", "0", "Pete Terhune");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("314", "2", "Rodger Bumpass");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("320", "1", "Ashley Edner");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("321", "2", "Paul Eiding");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("322", "0", "Katie Scarlettr");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("323", "2", "Bill Farmer");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("324", "0", "Keegan Farrell");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("325", "2", "Pat Fraley");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("326", "1", "Teresa Ganzel");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("327", "0", "Taylor Gifaldi");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("328", "2", "Marc John Jefferies");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("329", "2", "Joe Lala");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("330", "0", "Noah Luke");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("331", "0", "Sherry Lynn");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("332", "2", "Danny Mann");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("333", "0", "Mona Marshall");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("334", "0", "Mickie McGowan");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("335", "1", "Laraine Newman");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("336", "1", "Kay Panabaker");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("337", "0", "Bret 'Brook' Parker");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("338", "2", "Phil Proctor");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("339", "0", "Josh Qualtieri");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("340", "2", "Guido Quaroni");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("341", "2", "Jan Rabson");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("342", "1", "Lisa Raggio");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("343", "0", "Joe Ranft");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("345", "0", "Katherine Ringgold");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("351", "0", "Sophia Ranft");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("346", "2", "Bob Scott");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("349", "2", "Lee Unkrich");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("350", "2", "Wallace Shawn");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("352", "2", "Daniel Gerson");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("353", "2", "David Silverman");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1063", "2", "Donald Kerr");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1064", "0", "Mike Lally");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1065", "0", "Max Linder");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1066", "0", "Helen Lynd");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1067", "0", "Patricia Maier");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1068", "0", "Bertram Marburgh");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1069", "0", "Tony Merlo");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1070", "0", "Frank Milan");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1093", "2", "Charles Miller");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1094", "1", "Anna Mills");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1073", "0", "Frank Mills");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1074", "0", "Gerda Mora");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1075", "0", "Louis Natheaux");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1076", "0", "Hattie Noel");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1077", "0", "Rosa Palmese");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1078", "0", "Jane Patten");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1079", "0", "Hilda Plowright");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1080", "2", "Charles Quigley");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1081", "0", "Tom Quinn");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1082", "0", "Bill Ramsay");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1083", "2", "Joey Ray");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1084", "0", "Mel Ruick");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1085", "2", "Walter Sande");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1086", "2", "Larry Steers");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1087", "0", "Ray Teal");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1088", "0", "Gohr Van Vleck");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1089", "0", "Dorothy Vaughan");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1090", "2", "Theodore von Eltz");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1091", "0", "Joe Whitehead");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1092", "1", "Jan Wiley");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("385", "0", "Matthew O'Neill");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("386", "0", "Greg Beam");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("387", "0", "Erik Hellman");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("388", "0", "Nydia Rodriguez Terracina");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("389", "0", "Andy Luther");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("390", "0", "James Farruggio");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("391", "0", "Tom McElroy");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("392", "0", "James Fierro");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("393", "0", "Sam Derence");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("394", "1", "Jennifer Knox");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("395", "0", "Sophia Hinshelwood");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("396", "0", "Joseph Luis Caballero");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("397", "0", "Daryl Satcher");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("398", "0", "Chris Petschler");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("399", "0", "Aidan Feore");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("400", "0", "Walter Lewis");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("401", "0", "Nancy Crane");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("404", "0", "Michael Andrew Gorman");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("402", "0", "Lanny Lutz");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("403", "2", "Peter DeFaria");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("405", "0", "Helene Wilson");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("406", "2", "Joshua Rollins");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("407", "0", "Dale Rivera");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("408", "0", "Adam Kalesperis");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("409", "0", "Gertrude Kyles");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("410", "0", "James Scales");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("411", "0", "Nigel Carrington");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("412", "2", "Wai Wong");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("413", "0", "Michael Corey Foster");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("414", "0", "Hannah Gunn");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("415", "0", "Brandon Lambdin");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("357", "0", "Henry Milton Chu");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("367", "0", "Tom McComas");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1071", "0", "James Newman");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("365", "2", "Cameron Jack");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("355", "2", "Gary Sievers");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("356", "0", "Orion McCabe");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("368", "2", "London May");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("383", "2", "James Quinn");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1072", "2", "Felix Soper");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1101", "0", "Matt Berry");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1095", "0", "Charlotte Wilson Langley");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1096", "0", "Joshua Lassman");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1097", "1", "Carrie Lauren");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1098", "1", "Melissa LeEllen");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1099", "1", "Morgan Lester");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1100", "1", "Melinda D. Marin");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1102", "1", "Adrienne McQueen");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1103", "1", "Deana Molle'");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1104", "1", "Lindsey Marie Nelson");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1105", "0", "Jeremy Palko");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1106", "0", "B.J. Parker");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1107", "1", "Barrett Perlman");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1108", "1", "Maxi Schlereth");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1109", "1", "Nicole Alexandra Shipley");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1110", "1", "Veronica Viruet Simpson");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1111", "2", "John L. Smith Jr.");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1112", "1", "Hannah Stark");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1113", "0", "Chad Stevens");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1114", "0", "Michelle Stevenson");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1115", "1", "Makenzi Swicegood");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1116", "1", "Jennifer Thompson");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1117", "1", "Rachael Thompson");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1118", "1", "Victoria Vodar");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("1119", "0", "Kenny Waymack Jr.");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("829", "2", "Eric Edelstein");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("796", "2", "Jimmy Fallon");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("835", "2", "James DuMont");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("836", "0", "Matt Burke");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("837", "0", "Anna Talakkottur");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("838", "2", "Colin Trevorrow");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("795", "0", "Courtney J. Clark");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("797", "1", "Kelly Washington");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("834", "2", "Matthew Cardarople");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("833", "2", "Chad Randall");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("798", "0", "Yvonne Angulo");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("826", "1", "Chloe Perrin");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("825", "1", "Erika Erica");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("822", "1", "Tiffany Forest");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("376", "0", "Christopher Michael Stevens");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("377", "0", "Keith Harris");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("378", "0", "Kaveh Rastegar");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("380", "2", "Miles Anderson");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("354", "0", "Bobo Chang");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("344", "1", "Reshma Gajjar");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("375", "2", "Scott Hislop");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("374", "1", "Krystal Ellsworth");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("373", "1", "Sarah Mitchell");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("372", "0", "Gakenia Muigai");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("371", "0", "Mario Diaz");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("359", "0", "Julie Schmid");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("360", "0", "Lexie Contursi");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("364", "0", "Eartha Robinson");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("361", "0", "Sybil Azur");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("363", "1", "Tara Nicole Hughes");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("369", "0", "Kayla Kalbfleisch");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("366", "0", "Bill Prudich");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("362", "0", "Demian Boergadine");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("358", "2", "Gustavo Vargas");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("370", "0", "Kayla Bechor");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("379", "2", "Robert Roldan");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("440", "0", "Thom Findlay");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("381", "0", "Julien Bleitrach");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("382", "0", "Maxime Babara Touré");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("384", "0", "Pauline Hoarau");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("416", "0", "Christopher Swindel");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("417", "1", "Claire Tran");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("418", "0", "Alain Etoundi");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("419", "0", "Fayet Nsumoto");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("420", "0", "Kristina Kachinskaya");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("421", "0", "Veronika Khayla");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("422", "0", "Sissi Duparc");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("423", "0", "Noam Frost");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("424", "0", "Pauline Serreau");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("425", "0", "Philippe Rigot");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("426", "0", "Étienne Ménard");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("427", "0", "Peter Lamarque");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("428", "0", "Maximilien Seweryn");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("429", "0", "Zouheir Zerhouni");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("430", "0", "Tristan Zerbib");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("431", "0", "Elliot Jenicot");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("432", "0", "Staiv Gentis");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("433", "0", "Chloe Hollings");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("434", "0", "Aguendia Fotabong");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("435", "0", "Tania Dessources");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("436", "0", "Gaëtan Cotigny");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("437", "0", "François Bredon");
INSERT INTO Movie_Cast(id, gender, name) VALUES ("438", "0", "Cédric Chevalme");
